language: java
jdk:
    - oraclejdk7
    - oraclejdk8
    - openjdk7
branches:
  only:
    - master
install: /bin/true
script: "mvn clean install"
notifications:
  email:
    recipients:
      - dbpedia-developers@lists.sourceforge.net
    on_success: change
    on_failure: change
