sudo: false
language: java
jdk:
    - oraclejdk7
    - oraclejdk8
    - openjdk7
branches:
  only:
    - master
before_install:
  - sed -i.bak -e 's|https://nexus.codehaus.org/snapshots/|https://oss.sonatype.org/content/repositories/codehaus-snapshots/|g' ~/.m2/settings.xml
install: /bin/true
script: "mvn clean install"
notifications:
  email:
    recipients:
      - dbpedia-developers@lists.sourceforge.net
    on_success: change
    on_failure: change
